//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHang.Model
{
    using QuanLyKhoHang.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.InputInfoes = new HashSet<InputInfo>();
            this.OutputInfoes = new HashSet<OutputInfo>();
        }

        private int _IdEmployee;
        public int IdEmployee { get => _IdEmployee; set { _IdEmployee = value; OnPropertyChanged(); } }

        private string _NameEmployee;
        public string NameEmployee { get => _NameEmployee; set { _NameEmployee = value; OnPropertyChanged(); } }

        private Nullable<System.DateTime> _Birthday;
        public Nullable<System.DateTime> Birthday { get => _Birthday; set { _Birthday = value; OnPropertyChanged(); } }

        private Nullable<System.DateTime> _DateOfStart;
        public Nullable<System.DateTime> DateOfStart { get => _DateOfStart; set { _DateOfStart = value; OnPropertyChanged(); } }

        private int _IdRank;
        public int IdRank { get => _IdRank; set { _IdRank = value; OnPropertyChanged(); } }

        private int _IdStorage;
        public int IdStorage { get => _IdStorage; set { _IdStorage = value; OnPropertyChanged(); } }

        private string _PhoneNumber;
        public string PhoneNumber { get => _PhoneNumber; set { _PhoneNumber = value; OnPropertyChanged(); } }

        private string _AddressEmp;
        public string AddressEmp { get => _AddressEmp; set { _AddressEmp = value; OnPropertyChanged(); } }

        private string _Sex;
        public string Sex { get => _Sex; set { _Sex = value; OnPropertyChanged(); } }

        private string _ImageEmp;
        public string ImageEmp { get => _ImageEmp; set { _ImageEmp = value; OnPropertyChanged(); } }

        public virtual RankEmployee RankEmployee { get; set; }
        public virtual Storage Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputInfo> InputInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfoes { get; set; }
    }
}
