//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputInfo
    {
        public int IdInput { get; set; }
        public int IdConsignment { get; set; }
        public int IdEmployee { get; set; }
        public Nullable<int> Unit { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Input Input { get; set; }
        public virtual StorageDetail StorageDetail { get; set; }
    }
}
